<?php

namespace MP\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate()
    {
      $qb = $this->createQueryBuilder('a');

      $qb
         ->orderBy('a.datedebut', 'ASC')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
    
    public function findByUser($id)
    {
      $qb = $this->createQueryBuilder('a');

      $qb->where('a.user = :id')->setParameter('id', $id)
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }

    public function findByRecherche($id)
    {
  
    $recherche = $id;
      $qb = $this->createQueryBuilder('a');

      $qb   ->innerJoin('a.adresse', 'adr')
            ->innerJoin('a.categories', 'c')
            ->addSelect('adr')
            ->addSelect('c')
            ->where('a.title LIKE :id')
            ->orwhere('a.content LIKE :id')
            ->orwhere('a.id LIKE :id')
            ->orwhere('adr.ville LIKE :id')
            ->orwhere('c.name LIKE :id')
            
            ->setParameter('id', '%'.$recherche.'%')
            ->orderBy('a.datedebut', 'ASC')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
