<?php

namespace MP\PlatformBundle\Repository;

/**
 * listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listRepository extends \Doctrine\ORM\EntityRepository
{
}
